guard 'rspec', all_after_pass: false do
  #Custom Rails Tutorial specs
  watch(%r{^app/controllers/(.+)_(controller)\.rb$}) do |m|
    ["spec/routing/#{m[1]}_routing_spec.rb",
     "spec/#{m[2]}s/#{m[1]}_#{m[2]}_spec.rb",
     "spec/acceptance/#{m[1]}_spec.rb}",
     (m[1][/_pages/] ? "spec/requests/#{m[1]}_spec.rb":
                       "spec/requests/#{m[1].singularize}_pages_spec.rb")]
  end
end